---
k8s_images:
- etcd:3.4.3-0 
- kube-apiserver:v1.18.0
- kube-controller-manager:v1.18.0
- kube-scheduler:v1.18.0
- kube-proxy:v1.18.0
- coredns:1.6.7
- pause:3.2
- kube-registry-proxy:0.4
- nginx:1.17.9-alpine
flannel_images:
- quay.io/coreos/flannel:v0.12.0-amd64 
