apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kube-apiserver-proxy
    tier: control-plane
  name: kube-apiserver-proxy
  namespace: kube-system
spec:
  containers:
  - name: kube-apiserver-proxy
    image: nginx:1.17.9-alpine
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 250m
    volumeMounts:
    - mountPath: /etc/nginx/nginx.conf
      name: apiserver-proxy-conf
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - name: apiserver-proxy-conf
    hostPath:
      path: /etc/kubernetes/apiserver-proxy.conf
      type: File
