---
- name: remove old docker packages
  yum:
    name:
    - runc
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine
    - docker-engine-selinux
    state: absent

- name: install docker-ce yum-config-manager
  yum:
      name: "{{ packages }}"
      state: present
  vars:
      packages:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

- name: add docker-ce repo
  shell: yum-config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo

- name: install k8s required packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - container-selinux
    - libcgroup
    - ipvsadm
    - net-tools

- name: install tc package
  yum:
    name: tc
    state: present
  when: ansible_distribution_major_version != "7"

- name: install containerd.io
  shell: yum install https://mirrors.aliyun.com/docker-ce/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.10-3.2.el7.x86_64.rpm -y
  ignore_errors: yes

- name: install docker-ce rpms
  yum:
    name:
    - docker-ce-18.09.9
    - docker-ce-cli-18.09.9
    state: present
