---
- name: create /etc/docker if it is not present
  file:
    path: /etc/docker
    state: directory

- name: set cgroup driver to systemd
  copy:
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2",
        "storage-opts": [
          "overlay2.override_kernel_check=true"
        ]
      }
    dest: /etc/docker/daemon.json

- name: start docker service
  systemd:
    name: docker
    enabled: yes
    state: started

